### PR TITLE
Trying to clarify the hardwarwe

### PR DESCRIPTION
**Pull request by iriark01**
For https://jira.arm.com/browse/IOTDOCS-507

This will (I hope) solve the problem in the short term; the long term requires a chat with Chris Styles, but he's on holiday.

### CODE REVIEW

**Comment by iriark01** [comment]
So can you merge?

**Comment by kegilbert** [comment]
Looks like a travis job failed. I also don't have merge permissions to this repo. Pinging people below.
@cmonr 
@geky

**Comment by cmonr** [comment]
👍

**Comment by geky** [comment]
@kegilbert you should have merge permission? Let me know tomorrow if I'm wrong

**Pull request merged**
