### PR TITLE
Update license date in example source

### PR DESCRIPTION
**Pull request by davidsaada**

### CODE REVIEW

**Comment by AnotherButler** [comment]
Ping @dannybenor

**Comment by AnotherButler** [comment]
Do we know why Travis is failing?

**Comment by cmonr** [comment]
Wat. There's no reason that this should be failing with this PR....

@davidsaada Is it possible that commit 47d42eb4e297e882486e44dc24c48dc0295df399 was pushed directly to master? A quick glance at the commit history doesn't show any merge commits.

**Comment by davidsaada** [comment]
> 
> 
> Wat. There's no reason that this should be failing with this PR....
> 
> @davidsaada Is it possible that commit [47d42eb](https://github.com/ARMmbed/mbed-os-example-filesystem/commit/47d42eb4e297e882486e44dc24c48dc0295df399) was pushed directly to master? A quick glance at the commit history doesn't show any merge commits.

My bad, my bad. Didn't merge the travis fix PR. Just did it now.

**Comment by davidsaada** [comment]
Merged following travis success.

**Pull request merged**
